RHACS API and CLI
RHACS CLI Overview
Within RHACS ecosystem, roxctl is a command-line interface (CLI) for running commands on Red Hat Advanced Cluster Security for Kubernetes.

You can install the roxctl CLI to interact with Red Hat Advanced Cluster Security for Kubernetes from a command-line interface. You can install roxctl on Linux, Windows, or macOS. Follow the guide for installing roxtctl in your system.

For authentication, you can use an authentication token or your administrator password.

Red Hat recommends using an authentication token in a production environment because each token is assigned specific access control permissions.
RHACS CLI Integration
Navigate to the RHACS portal.

Go to Platform Configuration → Integrations.

Scroll down to the Authentication Tokens category, and click API Token.

Click Generate Token.

Enter a name for the token and select a role that provides the required level of access (for example, Continuous Integration or Sensor Creator).

Click Generate.

RHACS ROXCTL 1
After you have generated the authentication token, export it as ROX_API_TOKEN variable:


$ export ROX_API_TOKEN=<api_token>
$ export ROX_CENTRAL_ADDRESS=<address>:<port_number
Test the roxctl image check against a well known image to check the system policies and the CVEs that are detected:


$ roxctl --insecure-skip-tls-verify image check --endpoint $ROX_CENTRAL_ADDRESS:443 --image quay.io/centos7/httpd-24-centos7:centos7



=== Access the RHACS Central Services in the Student VM via the 'roxctl' Command

In this section, you use the `roxctl` command line tool to send commands to the RHACS server.

* In the provisioning email you received, note the following:
** The URL for the RHACS portal

[NOTE]
This information will be available in the services tab at link:https://demo.redhat.com/[demo.redhat.com^]. Or in the lab provisioning email.

.Procedure
. From the student VM, use the following command to verify your connection to RHACS Central:
*Sample input*
[source,bash,role="execute"]
----
roxctl --insecure-skip-tls-verify -e "$ROX_CENTRAL_ADDRESS:443" central whoami
----
*Sample output*
[source,bash]
----
User:
  auth-token:03b73fd3-313e-40a0-91f5-6ac88d8517a4
Roles:
 Admin, Analyst, Continuous Integration, None, Scope Manager, Sensor Creator, Vulnerability Management Approver, Vulnerability Management Requester, Vulnerability Report Creator
Access:
  rw APIToken
  rw Alert
  rw AllComments
  rw AuthPlugin
  rw AuthProvider
[... further access authorizations omitted for brevity ..]
----

=== Review Lab Access

You should now have access to the following
* Access to the OpenShift Web Console
* Access to the RHACS Web Console
* Access to the Linux Student VM that contains command line access to both
** OpenShift Cluster via 'oc' command
** RHACS Central services via 'roxctl' command
