=== Test Image Vulnerability Enforcement

After the enforcement is enabled, you can use `roxctl` to check any image for violations of this policy.
To run the image check, you need to know the exposed network endpoint for the Central component.

.Procedure
. Determine the OpenShift route to Central:
+
[source,sh]
----
CENTRAL=$( oc get route central -n stackrox -o json | jq -r '.spec.host' )
----
+
. Run the image check:
+
[source,sh]
----
roxctl -e $ROX_CENTRAL_ADDRESS:443 image check --image docker.io/vulnerables/cve-2017-7494 --insecure-skip-tls-verify
----
+
.Example Output
[source,texinfo,options="nowrap"]
----
(TOTAL: 5, LOW: 4, MEDIUM: 0, HIGH: 1, CRITICAL: 0)

+--------------------------------+----------+--------------+--------------------------------+--------------------------------+--------------------------------+
|             POLICY             | SEVERITY | BREAKS BUILD |          DESCRIPTION           |           VIOLATION            |          REMEDIATION           |
+--------------------------------+----------+--------------+--------------------------------+--------------------------------+--------------------------------+
|   Fixable Severity at least    |   HIGH   |      X       |   Alert on deployments with    | - Fixable CVE-2016-2090 (CVSS  |  Use your package manager to   |
|           Important            |          |              |  fixable vulnerabilities with  | 9.8) (severity Critical) found |  update to a fixed version in  |
|                                |          |              |   a Severity Rating at least   | in component 'libbsd' (version |  future builds or speak with   |
|                                |          |              |           Important            | 0.7.0-2), resolved by version  | your security team to mitigate |
|                                |          |              |                                |         0.7.0-2+deb8u1         |      the vulnerabilities.      |
|                                |          |              |                                |                                |                                |

[ ... MANY SPECIFIC CVE VIOLATIONS OMITTED ... ]
[ ... MANY SPECIFIC CVE VIOLATIONS OMITTED ... ]
[ ... MANY SPECIFIC CVE VIOLATIONS OMITTED ... ]

|                                |          |              |                                |                                |       image to the code.       |
+--------------------------------+----------+--------------+--------------------------------+--------------------------------+--------------------------------+
|   Ubuntu Package Manager in    |   LOW    |      -       |      Alert on deployments      |   - Image includes component   |    Run `dpkg -r --force-all    |
|             Image              |          |              |     with components of the     |   'apt' (version 1.0.9.8.4)    |     apt apt-get && dpkg -r     |
|                                |          |              |     Debian/Ubuntu package      |                                |  --force-all debconf dpkg` in  |
|                                |          |              |    management system in the    |   - Image includes component   | the image build for production |
|                                |          |              |             image.             |    'dpkg' (version 1.17.27)    |          containers.           |
+--------------------------------+----------+--------------+--------------------------------+--------------------------------+--------------------------------+
WARN:	A total of 5 policies have been violated
ERROR:	failed policies found: 1 policies violated that are failing the check
ERROR:	Policy "Fixable Severity at least Important" - Possible remediation: "Use your package manager to update to a fixed version in future builds or speak with your security team to mitigate the vulnerabilities."
ERROR:	checking image failed after 3 retries: failed policies found: 1 policies violated that are failing the check
----
When `roxctl` runs an image check, it requests Central to perform the check, evaluate policies, and return the result. Any policy violations are displayed, informing the user of the policy's _rationale_ and any _remediation_ steps. Policy failure is indicated by the process return code of `roxctl`. A zero value indicates success (no policy violation), while a non-zero value indicates failure (policy violations).
+
NOTE: Because vulnerabilities change often, your output results for the particular CVEs in this image may vary.
This output is truncated to improve readability.