apiVersion: perses.dev/v1alpha2
kind: PersesDatasource
metadata:
  name: sample-stackrox-datasource
  namespace: stackrox
spec:
  client:
    tls:
      caCert:
        certPath: /ca/service-ca.crt
        type: file
      enable: true
  config:
    default: true
    display:
      name: RHACS Prometheus Datasource
    plugin:
      kind: PrometheusDatasource
      spec:
        proxy:
          kind: HTTPProxy
          spec:
            url: 'http://sample-stackrox-monitoring-stack-prometheus.stackrox.svc.cluster.local:9090'