apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app
  namespace: 301-02-python
  labels:
    app: python-app
    app.kubernetes.io/part-of: openshift-security-roadshow
    app.kubernetes.io/component: 301-02-gitops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      serviceAccountName: app
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: app
          image: registry.access.redhat.com/ubi9/python-311:latest
          imagePullPolicy: IfNotPresent
          command: ["python3", "-m", "http.server", "8080"]
          ports:
            - containerPort: 8080
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
            runAsNonRoot: true
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
