apiVersion: v1
kind: Namespace
metadata:
  name: 301-02-python
  labels:
    app.kubernetes.io/part-of: openshift-security-roadshow
    app.kubernetes.io/component: 301-02-gitops
    stride.example.com/app: python
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
