apiVersion: v1
kind: ServiceAccount
metadata:
  name: app
  namespace: 301-02-python
  labels:
    app.kubernetes.io/part-of: openshift-security-roadshow
    app.kubernetes.io/component: 301-02-gitops
automountServiceAccountToken: false
