apiVersion: v1
kind: Service
metadata:
  name: python-app
  namespace: 301-02-python
  labels:
    app: python-app
    app.kubernetes.io/part-of: openshift-security-roadshow
    app.kubernetes.io/component: 301-02-gitops
spec:
  selector:
    app: python-app
  ports:
    - name: http
      port: 8080
      targetPort: 8080
